authors/urls.py
from django.urls import path
from . import views

app_name = "authors"

urlpatterns = [
    path("add/", views.add, name="add"),
    path("", views.authors, name="authors"),
    path("<int:author_id>", views.details, name="details"),
    path("scrape/", views.scrape, name="scrape"),
]

myquotes/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("quotesapp.urls")),
    path("users/", include("users.urls")),
    path("authors/", include("authors.urls")),
    path("tags/", include("tags.urls")),
]

tags/urls.py
from django.urls import path
from . import views

app_name = "tags"

urlpatterns = [
    path("add/", views.add, name="add"),
    path("", views.tags, name="tags"),
    path("<int:tag_id>", views.quotes_with_tag, name="details"),
]

authors/forms.py
from django.forms import (
    ModelForm,
    CharField,
    TextInput,
    Textarea,
)

from quotesapp.models import Author


class AuthorForm(ModelForm):
    fullname = CharField(max_length=255, widget=TextInput())
    born_date = CharField(max_length=20, widget=TextInput())
    born_location = CharField(max_length=255, widget=TextInput())
    description = CharField(max_length=1500, widget=Textarea())

    class Meta:
        model = Author
        fields = ["fullname", "born_date", "born_location", "description"]

authors/views.py
from django.shortcuts import get_object_or_404, render, redirect
from quotesapp.models import Author, Quote
from authors.forms import AuthorForm
from django.core.paginator import Paginator
from scrap.scrap_quote_data import scrap_author_details


def authors(request):
    paginator = Paginator(Author.objects.all().order_by("fullname"), 8)
    page = request.GET.get("page")
    authors = paginator.get_page(page)
    return render(request, "authors/display.html", {"authors": authors})


def details(request, author_id):
    author = get_object_or_404(Author, pk=author_id)
    quotes_by_author = Quote.objects.filter(author_id=author_id)
    return render(
        request, "authors/details.html", {"author": author, "quotes": quotes_by_author}
    )


def add(request):
    if request.method == "POST":
        form = AuthorForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect(to="quotesapp:main")
        else:
            return render(request, "authors/author.html", {"form": form})

    return render(request, "authors/author.html", {"form": AuthorForm()})


def scrape(request):
    author_details = scrap_author_details()
    for author_scraped in author_details:
        new_author = Author(
            fullname=author_scraped.fullname,
            born_date=author_scraped.born_date,
            born_location=author_scraped.born_location,
            description=author_scraped.description,
        )
        new_author.save()
    return redirect(to="authors:authors")

authors/templates/authors/author.html
{% extends "base.html" %}

{% block content %}
<b>Add new author below or:</b> <a href="{% url 'authors:scrape' %}" role="button" class="primary outline">Scrape authors from quotes.toscrape.com</a>
<form method="POST" action="{% url 'authors:add' %}">
    {% csrf_token %}
    <div style="padding: 10px">
        <label><b>Enter author details:</b>
            {{form.as_p}}
        </label>

        <span>{{ form.errors.name }}</span>
    </div>
    <div class="grid">
        <button type="submit">Submit</button>
        <button type="reset" class="secondary">Reset</button>
    </div>
</form>

{% endblock %}

authors/templates/authors/details.html
{% extends "base.html" %}

{% block content %}
<div class="author-details">
    <h1>Author Details</h1>
    <div class="field">
        <span>Full Name:</span>
        <span>{{ author.fullname }}</span>
    </div>
    <div class="field">
        <span>Date of Birth:</span>
        <span>{{ author.born_date }}</span>
    </div>
    <div class="field">
        <span>Place of Birth:</span>
        <span>{{ author.born_location }}</span>
    </div>
    <div class="field">
        <span>Description:</span>
        <p>{{ author.description }}</p>
    </div>
</div>
<h4>{{ author.fullname }}'s quotes:</h4>
{% for quote in quotes %}
    <ul>
        <li>
            <p>{{ quote.quote }}</p>
        </li>
    </ul>
    {% endfor %}
{% endblock %}

authors/templates/authors/display.html
{% extends "base.html" %}

{% block content %}

{% for author in authors %}
    <ul>
        <li>
            <a href="{% url 'authors:details' author.id %}" role="button" class="primary outline">{{ author.fullname }}</a>
        </li>
    </ul>
    {% endfor %}
<hr><br/>

{% if authors.has_previous %}
    <a href="?page=1">&laquo First</a>
    <a href="?page={{authors.previous_page_number}}">Previous</a>

{% endif %}

Page {{authors.number}} of {{authors.paginator.num_pages}}

{% if authors.has_next %}
    <a href="?page={{authors.next_page_number}}">Next</a>
    <a href="?page={{authors.paginator.num_pages}}">Last &raquo</a>

{% endif %}

{% endblock %}