authors/urls.py
from django.urls import path
from . import views

app_name = "authors"

urlpatterns = [
    path("add/", views.add, name="add"),
    path("", views.authors, name="authors"),
    path("<int:author_id>", views.details, name="details"),
    path("scrape/", views.scrape, name="scrape"),
]

myquotes/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("quotesapp.urls")),
    path("users/", include("users.urls")),
    path("authors/", include("authors.urls")),
    path("tags/", include("tags.urls")),
]

quotesapp/urls.py
from django.urls import path
from . import views

app_name = "quotesapp"

urlpatterns = [
    path("", views.main, name="main"),
    path("quotes/", views.quotes, name="quotes"),
    path("quotes/add/", views.add, name="add"),
    path("quotes/scrape/", views.scrape, name="scrape"),
]

tags/urls.py
from django.urls import path
from . import views

app_name = "tags"

urlpatterns = [
    path("add/", views.add, name="add"),
    path("", views.tags, name="tags"),
    path("<int:tag_id>", views.quotes_with_tag, name="details"),
]

users/urls.py
from django.urls import path
from . import views
from django.contrib.auth.views import (
    PasswordResetDoneView,
    PasswordResetConfirmView,
    PasswordResetCompleteView,
)

app_name = "users"

urlpatterns = [
    path("signup/", views.signupuser, name="signup"),
    path("login/", views.loginuser, name="login"),
    path("logout/", views.logoutuser, name="logout"),
    path("reset-password/", views.ResetPasswordView.as_view(), name="password_reset"),
    path(
        "reset-password/done/",
        PasswordResetDoneView.as_view(template_name="users/password_reset_done.html"),
        name="password_reset_done",
    ),
    path(
        "reset-password/confirm/<uidb64>/<token>/",
        PasswordResetConfirmView.as_view(
            template_name="users/password_reset_confirm.html",
            success_url="/users/reset-password/complete/",
        ),
        name="password_reset_confirm",
    ),
    path(
        "reset-password/complete/",
        PasswordResetCompleteView.as_view(
            template_name="users/password_reset_complete.html"
        ),
        name="password_reset_complete",
    ),
]

quotesapp/models.py
from django.db import models


class Tag(models.Model):
    name = models.CharField(max_length=255, unique=True)

    def __str__(self) -> str:
        return self.name


class Author(models.Model):
    fullname = models.CharField(max_length=255, unique=True)
    born_date = models.CharField(max_length=20)
    born_location = models.CharField(max_length=255)
    description = models.TextField()

    def __str__(self) -> str:
        return self.fullname


class Quote(models.Model):
    quote = models.TextField(unique=True)
    author = models.ForeignKey(Author, on_delete=models.CASCADE)
    tags = models.ManyToManyField(Tag)

    def __str__(self) -> str:
        return self.quote

authors/forms.py
from django.forms import (
    ModelForm,
    CharField,
    TextInput,
    Textarea,
)

from quotesapp.models import Author


class AuthorForm(ModelForm):
    fullname = CharField(max_length=255, widget=TextInput())
    born_date = CharField(max_length=20, widget=TextInput())
    born_location = CharField(max_length=255, widget=TextInput())
    description = CharField(max_length=1500, widget=Textarea())

    class Meta:
        model = Author
        fields = ["fullname", "born_date", "born_location", "description"]

quotesapp/forms.py
from django.forms import (
    ModelForm,
    CharField,
    ModelMultipleChoiceField,
    ModelChoiceField,
    TextInput,
    CheckboxSelectMultiple,
)
from .models import Tag, Author, Quote


class QuoteForm(ModelForm):
    quote = CharField(max_length=1000, widget=TextInput())

    author = ModelChoiceField(queryset=Author.objects.all())

    tags = ModelMultipleChoiceField(
        queryset=Tag.objects.all(), widget=CheckboxSelectMultiple
    )

    class Meta:
        model = Quote
        fields = ["quote", "author", "tags"]

tags/forms.py
from django.forms import (
    ModelForm,
    CharField,
    TextInput,
)

from quotesapp.models import Tag


class TagForm(ModelForm):

    name = CharField(min_length=3, max_length=25, widget=TextInput())

    class Meta:
        model = Tag
        fields = ["name"]

authors/views.py
from django.shortcuts import get_object_or_404, render, redirect
from quotesapp.models import Author, Quote
from authors.forms import AuthorForm
from django.core.paginator import Paginator
from scrap.scrap_quote_data import scrap_author_details


def authors(request):
    paginator = Paginator(Author.objects.all().order_by("fullname"), 8)
    page = request.GET.get("page")
    authors = paginator.get_page(page)
    return render(request, "authors/display.html", {"authors": authors})


def details(request, author_id):
    author = get_object_or_404(Author, pk=author_id)
    quotes_by_author = Quote.objects.filter(author_id=author_id)
    return render(
        request, "authors/details.html", {"author": author, "quotes": quotes_by_author}
    )


def add(request):
    if request.method == "POST":
        form = AuthorForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect(to="quotesapp:main")
        else:
            return render(request, "authors/author.html", {"form": form})

    return render(request, "authors/author.html", {"form": AuthorForm()})


def scrape(request):
    author_details = scrap_author_details()
    for author_scraped in author_details:
        new_author = Author(
            fullname=author_scraped.fullname,
            born_date=author_scraped.born_date,
            born_location=author_scraped.born_location,
            description=author_scraped.description,
        )
        new_author.save()
    return redirect(to="authors:authors")

quotesapp/views.py
from django.shortcuts import get_object_or_404, redirect, render
from quotesapp.forms import QuoteForm
from quotesapp.models import Quote, Tag, Author
from django.core.paginator import Paginator
from scrap.scrap_quote_data import scrap_quotes


def main(request):
    return render(request, "quotesapp/index.html")


def quotes(request):
    quotes = Quote.objects.all()
    extracted_tags = [quote.tags.all() for quote in quotes]
    paginator = Paginator(list(zip(quotes, extracted_tags)), 5)
    page = request.GET.get("page")
    quotes_and_tags = paginator.get_page(page)
    return render(request, "quotesapp/display.html", {"quotes": quotes_and_tags})


def add(request):
    if request.method == "POST":
        form = QuoteForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect(to="quotesapp:main")
        else:
            return render(request, "quotesapp/quote.html", {"form": form})

    return render(request, "quotesapp/quote.html", {"form": QuoteForm()})


def scrape(request):
    quotes = scrap_quotes()
    for quote in quotes:
        author = get_object_or_404(Author, fullname=quote.author)
        try:
            new_quote = Quote.objects.get(quote=quote.quote)
        except Quote.DoesNotExist:
            new_quote = Quote.objects.create(quote=quote.quote, author=author)
            for tagname in quote.tags:
                try:
                    tag = Tag.objects.get(name=tagname)
                except Tag.DoesNotExist:
                    tag = Tag.objects.create(name=tagname)
                new_quote.tags.add(tag)

    return redirect(to="quotesapp:quotes")

tags/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponseNotFound
from quotesapp.models import Quote, Tag
from tags.forms import TagForm


def tags(request):
    tags = Tag.objects.all().order_by("name")
    return render(request, "tags/display.html", {"tags": tags})


def add(request):
    if request.method == "POST":
        form = TagForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect(to="quotesapp:main")
        else:
            return render(request, "tags/tag.html", {"form": form})

    return render(request, "tags/tag.html", {"form": TagForm()})


def quotes_with_tag(request, tag_id):
    try:
        tag = Tag.objects.get(id=tag_id)
    except Tag.DoesNotExist:
        return HttpResponseNotFound("Tag does not exist")
    quotes = Quote.objects.filter(tags__id=tag_id)
    extracted_tags = [quote.tags.all() for quote in quotes]
    return render(
        request,
        "tags/details.html",
        {"quotes": zip(quotes, extracted_tags), "sel_tag": tag},
    )

quotesapp/templates/quotesapp/author.html
{% extends "quotesapp/base.html" %}

{% block content %}

<form method="POST" action="{% url 'quotesapp:authors' %}">
    {% csrf_token %}
    <div style="padding: 10px">
        <label>Enter author details:
            {{form.as_p}}
        </label>

        <span>{{ form.errors.name }}</span>
    </div>
    <div class="grid">
        <button type="submit">Submit</button>
        <button type="reset" class="secondary">Reset</button>
    </div>
</form>

{% endblock %}

quotesapp/templates/quotesapp/base.html
<!DOCTYPEhtml>
<html lang="en">
<head>
    <meta charset="UTF-8"/>
    <title>Note information</title>
    <link rel="stylesheet" href="https://unpkg.com/@picocss/pico@latest/css/pico.min.css"/>
    {% load static %}
    <link rel="stylesheet" href="{% static 'quotesapp/style.css' %}">
</head>
<body>
<main class="container">
    <nav style="margin-bottom: 20px; border-bottom: 2px solid; padding-left: 30px">
        <ul>
            <li><a href="/" role="button"> Home </a></li>
            <li><a href="{% url 'quotesapp:authors' %}" role="button"> Authors </a></li>
            <li><a href="{% url 'quotesapp:quotes' %}" role="button"> Quotes </a></li>
        </ul>
        {% if user.is_authenticated %}
        <ul>
            <li><a href="{% url 'quotesapp:authors' %}" role="button">Add author</a></li>
            <li><a href="{% url 'quotesapp:quotes' %}" role="button">Add quote</a></li>
            <li><a href="{% url 'quotesapp:tags' %}" role="button">Add tag</a></li>
        </ul>
        <ul>
            <li>Welcome <b>{{ user.username }}!</b></li>
            <li><a href="{% url 'users:logout' %}" role="button">Logout</a></li>
        </ul>
        {% else %}
        <ul>
            <li><a href="{% url 'users:signup' %}" role="button">Sign Up</a></li>
            <li><a href="{% url 'users:login' %}" role="button">Login</a></li>
        </ul>
        {% endif %}
    </nav>
    {% block content %} {% endblock %}
</main>
</body>
</html>

quotesapp/templates/quotesapp/display.html
{% extends "base.html" %}

{% block content %}

{% for quote, tags in quotes %}
    <ul>
        <li>
            <p>{{ quote.quote }}</p>
            <a href="{% url 'authors:details' quote.author.id %}" role="button" class="primary outline">{{ quote.author.fullname }}</a>
            {% for tag in tags %}
            <a href="{% url 'tags:details' tag.id %}" role="button" class="secondary outline"># {{ tag.name }}</a>
            {% endfor %}

        </li>
    </ul>
    {% endfor %}

<hr><br/>

{% if quotes.has_previous %}
    <a href="?page=1">&laquo First</a>
    <a href="?page={{quotes.previous_page_number}}">Previous</a>

{% endif %}

Page {{quotes.number}} of {{quotes.paginator.num_pages}}

{% if quotes.has_next %}
    <a href="?page={{quotes.next_page_number}}">Next</a>
    <a href="?page={{quotes.paginator.num_pages}}">Last &raquo</a>

{% endif %}

{% endblock %}

quotesapp/templates/quotesapp/index.html
{% extends "base.html" %}

quotesapp/templates/quotesapp/quote.html
{% extends "base.html" %}

{% block content %}
<b>Add new quote below or:</b> <a href="{% url 'quotesapp:scrape' %}" role="button" class="primary outline">Scrape quotes from quotes.toscrape.com</a>
<form method="POST" action="{% url 'quotesapp:add' %}">
    {% csrf_token %}
    <div style="padding: 10px">
        <label>Enter quote details:
            {{form.as_p}}
        </label>

        <span>{{ form.errors.name }}</span>
    </div>
    <div class="grid">
        <button type="submit">Submit</button>
        <button type="reset" class="secondary">Reset</button>
    </div>
</form>

{% endblock %}

quotesapp/templates/quotesapp/tag.html
{% extends "base.html" %}

{% block content %}

<form method="POST" action="{% url 'quotesapp:tags' %}">
    {% csrf_token %}
    <div style="padding: 10px">
        <label>Enter the tag name:
            {{form.name}}
        </label>
        <span>{{ form.errors.name }}</span>
    </div>
    <div class="grid">
        <button type="submit">Submit</button>
        <button type="reset" class="secondary">Reset</button>
    </div>
</form>

{% endblock %}