authors/urls.py
from django.urls import path
from . import views

app_name = "authors"

urlpatterns = [
    path("add/", views.add, name="add"),
    path("", views.authors, name="authors"),
    path("<int:author_id>", views.details, name="details"),
    path("scrape/", views.scrape, name="scrape"),
]

myquotes/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("quotesapp.urls")),
    path("users/", include("users.urls")),
    path("authors/", include("authors.urls")),
    path("tags/", include("tags.urls")),
]

quotesapp/urls.py
from django.urls import path
from . import views

app_name = "quotesapp"

urlpatterns = [
    path("", views.main, name="main"),
    path("quotes/", views.quotes, name="quotes"),
    path("quotes/add/", views.add, name="add"),
    path("quotes/scrape/", views.scrape, name="scrape"),
]

tags/urls.py
from django.urls import path
from . import views

app_name = "tags"

urlpatterns = [
    path("add/", views.add, name="add"),
    path("", views.tags, name="tags"),
    path("<int:tag_id>", views.quotes_with_tag, name="details"),
]

users/urls.py
from django.urls import path
from . import views
from django.contrib.auth.views import (
    PasswordResetDoneView,
    PasswordResetConfirmView,
    PasswordResetCompleteView,
)

app_name = "users"

urlpatterns = [
    path("signup/", views.signupuser, name="signup"),
    path("login/", views.loginuser, name="login"),
    path("logout/", views.logoutuser, name="logout"),
    path("reset-password/", views.ResetPasswordView.as_view(), name="password_reset"),
    path(
        "reset-password/done/",
        PasswordResetDoneView.as_view(template_name="users/password_reset_done.html"),
        name="password_reset_done",
    ),
    path(
        "reset-password/confirm/<uidb64>/<token>/",
        PasswordResetConfirmView.as_view(
            template_name="users/password_reset_confirm.html",
            success_url="/users/reset-password/complete/",
        ),
        name="password_reset_confirm",
    ),
    path(
        "reset-password/complete/",
        PasswordResetCompleteView.as_view(
            template_name="users/password_reset_complete.html"
        ),
        name="password_reset_complete",
    ),
]

templates/base.html
<!DOCTYPEhtml>
<html lang="en">
<head>
    <meta charset="UTF-8"/>
    <title>Note information</title>
    <link rel="stylesheet" href="https://unpkg.com/@picocss/pico@latest/css/pico.min.css"/>
    {% load static %}
    <link rel="stylesheet" href="{% static 'quotesapp/style.css' %}">
</head>
<body>
<main class="container">
    <nav style="margin-bottom: 20px; border-bottom: 2px solid; padding-left: 30px">
        <ul>
            <li><a href="/" role="button"> Home </a></li>
            <li><a href="{% url 'authors:authors' %}" role="button"> Authors </a></li>
            <li><a href="{% url 'quotesapp:quotes' %}" role="button"> Quotes </a></li>
            <li><a href="{% url 'tags:tags' %}" role="button"> Tags </a></li>
        </ul>
        {% if user.is_authenticated %}
        <ul>
            <li><a href="{% url 'authors:add' %}" role="button">Add author</a></li>
            <li><a href="{% url 'quotesapp:add' %}" role="button">Add quote</a></li>
            <li><a href="{% url 'tags:add' %}" role="button">Add tag</a></li>
        </ul>
        <ul>
            <li>Welcome <b>{{ user.username }}!</b></li>
            <li><a href="{% url 'users:logout' %}" role="button">Logout</a></li>
        </ul>
        {% else %}
        <ul>
            <li><a href="{% url 'users:signup' %}" role="button">Sign Up</a></li>
            <li><a href="{% url 'users:login' %}" role="button">Log in</a></li>
        </ul>
        {% endif %}
    </nav>
    {% block content %} {% endblock %}
</main>
</body>
</html>